// KCode - Audit Engine Types
// Core types for the deterministic audit pipeline.

export type Severity = "critical" | "high" | "medium" | "low";
export type Language =
  | "c" | "cpp" | "python" | "go" | "rust"
  | "javascript" | "typescript" | "swift" | "java"
  | "kotlin" | "csharp" | "php" | "ruby" | "dart"
  | "scala" | "elixir" | "lua" | "zig" | "haskell"
  | "perl" | "r" | "julia" | "sql" | "matlab" | "shell";

/**
 * A bug pattern is a rule that identifies a specific class of dangerous code.
 * Patterns are the core of the audit engine — they transform "the model looks
 * for bugs" (unreliable) into "the pipeline looks for KNOWN dangerous patterns,
 * then asks the model to verify each one" (reliable).
 */
export interface BugPattern {
  /** Stable unique ID, used for tracking and reporting */
  id: string;
  /** Short human-readable title */
  title: string;
  /** Severity if the pattern is confirmed as a real bug */
  severity: Severity;
  /** Languages this pattern applies to */
  languages: Language[];
  /** Regex (multi-line aware) to locate candidate sites */
  regex: RegExp;
  /** Short explanation shown in the report */
  explanation: string;
  /** The specific question the model must answer to verify */
  verify_prompt: string;
  /** CWE reference, if applicable */
  cwe?: string;
  /** Suggested fix template (human-readable) */
  fix_template?: string;
}

/** A candidate finding — a pattern match that hasn't been verified yet. */
export interface Candidate {
  pattern_id: string;
  severity: Severity;
  file: string;
  line: number;
  matched_text: string;
  context: string; // surrounding lines
}

/** Verification result from the model. */
export type VerifyVerdict = "confirmed" | "false_positive" | "needs_context";

export interface Verification {
  verdict: VerifyVerdict;
  reasoning: string;
  execution_path?: string;
  suggested_fix?: string;
}

/** A confirmed finding ready to go into the report. */
export interface Finding {
  pattern_id: string;
  pattern_title: string;
  severity: Severity;
  file: string;
  line: number;
  matched_text: string;
  context: string;
  verification: Verification;
  cwe?: string;
}

/**
 * Proof-of-concept exploit for a confirmed finding.
 *
 * Generated by the exploit-gen module AFTER verification. Proves the
 * finding is exploitable by providing a concrete attack payload, the
 * delivery vector, and the expected outcome. This is the difference
 * between "this pattern matched" and "an attacker can do X".
 */
export interface ExploitProof {
  /** The finding this exploit targets */
  pattern_id: string;
  /** File + line reference */
  file: string;
  line: number;
  /** How the attack is delivered (e.g., "malformed HID packet", "crafted JSON API response") */
  attack_vector: string;
  /** The concrete malicious input / payload */
  payload: string;
  /** What happens when the exploit fires */
  expected_result: string;
  /** Step-by-step reproduction instructions */
  reproduction_steps: string[];
  /** CVSS-like severity justification */
  severity_justification: string;
  /** CWE reference from the pattern */
  cwe?: string;
}

/** Result of the full audit pipeline. */
export interface AuditResult {
  project: string;
  timestamp: string;
  languages_detected: Language[];
  files_scanned: number;
  candidates_found: number;
  confirmed_findings: number;
  false_positives: number;
  findings: Finding[];
  exploits?: ExploitProof[];
  elapsed_ms: number;
}
