// KCode - Fullstack Engine: Frontend + Backend + DB in one command
//
// "create a fullstack app for task management"
// → Web engine: Next.js frontend with cinematic effects
// → API engine: Express API with CRUD routes
// → DB: SQLite with auto-migrations
// → All wired together

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createApiProject } from "./api-engine";
import { createWebProject } from "./web-engine";

export interface FullstackResult {
  name: string;
  frontend: { path: string; files: number; machineFiles: number; llmFiles: number };
  backend: { path: string; files: number; entities: string[] };
  totalFiles: number;
  prompt: string;
}

export function createFullstackProject(userRequest: string, cwd: string): FullstackResult {
  // Extract project name
  const nameMatch = userRequest.match(/(?:called|named|nombre|for|para)\s+(\w[\w-]*)/i);
  const name = nameMatch?.[1] ?? "my-app";

  const projectPath = join(cwd, name);
  mkdirSync(projectPath, { recursive: true });

  // Create frontend
  const webResult = createWebProject(userRequest, projectPath);

  // Create backend
  const apiResult = createApiProject(userRequest, projectPath);

  // Create docker-compose for the full stack
  writeFileSync(
    join(projectPath, "docker-compose.yml"),
    `version: "3.8"
services:
  frontend:
    build: ./${webResult.intent.name}
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build: ./${apiResult.projectPath.split("/").pop()}
    ports:
      - "3001:3001"
    volumes:
      - db-data:/app/data

volumes:
  db-data:
`,
  );

  // Monorepo package.json
  writeFileSync(
    join(projectPath, "package.json"),
    JSON.stringify(
      {
        name,
        private: true,
        scripts: {
          dev: `concurrently "cd ${webResult.intent.name} && npm run dev" "cd ${apiResult.projectPath.split("/").pop()} && npm run dev"`,
          "dev:frontend": `cd ${webResult.intent.name} && npm run dev`,
          "dev:backend": `cd ${apiResult.projectPath.split("/").pop()} && npm run dev`,
          install: `cd ${webResult.intent.name} && npm install && cd ../${apiResult.projectPath.split("/").pop()} && npm install`,
          build: `cd ${webResult.intent.name} && npm run build && cd ../${apiResult.projectPath.split("/").pop()} && npm run build`,
        },
        devDependencies: { concurrently: "^9.0.0" },
      },
      null,
      2,
    ),
  );

  writeFileSync(
    join(projectPath, "README.md"),
    `# ${name}

Full-stack application generated by KCode.

## Structure

\`\`\`
${name}/
├── ${webResult.intent.name}/          # Frontend (${webResult.intent.stack})
├── ${apiResult.projectPath.split("/").pop()}/             # Backend API (Express + SQLite)
├── docker-compose.yml  # Docker orchestration
└── package.json        # Monorepo scripts
\`\`\`

## Quick Start

\`\`\`bash
npm install
npm run dev
\`\`\`

Frontend: http://localhost:3000
API: http://localhost:3001

## API Endpoints

${apiResult.entities
  .map(
    (e) => `- \`GET /api/${e.name}s\` — list all ${e.name}s
- \`POST /api/${e.name}s\` — create ${e.name}
- \`GET /api/${e.name}s/:id\` — get ${e.name}
- \`PUT /api/${e.name}s/:id\` — update ${e.name}
- \`DELETE /api/${e.name}s/:id\` — delete ${e.name}`,
  )
  .join("\n\n")}
`,
  );

  writeFileSync(join(projectPath, ".gitignore"), "node_modules/\ndist/\n.next/\ndata.db\n.env\n");

  const totalFiles = webResult.template.files.length + apiResult.files.length + 4; // +4 for monorepo files

  const prompt = `You are setting up a fullstack application. The machine already created:

FRONTEND: ${webResult.intent.name}/ (${webResult.intent.stack}, ${webResult.template.files.length} files)
BACKEND: ${apiResult.projectPath.split("/").pop()}/ (Express + SQLite, ${apiResult.files.length} files)
ENTITIES: ${apiResult.entities.map((e) => e.name).join(", ")}

The frontend and backend are already connected. You need to:
1. Customize the frontend content (hero, features, etc.)
2. Add business logic to the API routes (validation rules, relationships)
3. Wire the frontend to call the API endpoints
4. Add proper error handling

USER REQUEST: "${userRequest}"

Start by customizing the frontend, then improve the API business logic.`;

  return {
    name,
    frontend: {
      path: webResult.projectPath,
      files: webResult.template.files.length,
      machineFiles: webResult.machineFiles,
      llmFiles: webResult.llmFiles,
    },
    backend: {
      path: apiResult.projectPath,
      files: apiResult.files.length,
      entities: apiResult.entities.map((e) => e.name),
    },
    totalFiles,
    prompt,
  };
}
